### ISSUE TITLE
mkv videos and variable frame rate

### ISSUE THREAD

**Issue by DarkShadow44** [Anime4000/IFME#13]
Mkv videos that are variable frame rate get detected as having CFR (probably an MediaInfo bug). This leads to the video going out of sync.
````
//frmMain.cs

if (String.Equals(video[0].frameRateMode, "VFR"))
````
If this piece of code gets removed it works as expected. It also seemed to work with constant frame rate videos, but I am not sure why this check is needed so maybe it just needs to be adjusted.

Aditionally, since v0.4.1.9 some videos are only partially encoded, for example only the first 147 frames.
I got it to work after changing the following code
````
//frmMain.cs

//old code
args[2] = String.Format("-f yuv4mpegpipe -s {0} -vsync passthrough", screen[x]);

//new code
args[2] = String.Format("-f yuv4mpegpipe -s {0} -vsync vfr", screen[x]);
````
It seemed to work for constant frame rate video too, though I don't really know the implications of that change.

**Comment by Anime4000** [comment]
Upon checking MediaInfo Wrapper: https://github.com/Anime4000/IFME/blob/master/ifme.framework/MediaInfoDotNet/Models/MultiStreamCommon.cs#L408

This code I added manually, I tried a DVD ripped to MKV (MakeMKV) it detect as expected as in my end.

Another code I added: https://github.com/Anime4000/IFME/blob/master/ifme.framework/MediaInfoDotNet/Models/MultiStreamCommon.cs#L395

This allow returning Top or Bottom Fields, allowing FFmpeg deinterlaced before sending to x265, I split each fileds into different frame, become double fps it's original, this test file I have on my disk, I capture FIFA 2014 via TV card and convert. 25fps become 50fps, smooth animation.

since interlaced video operate in constant frame rate, I not sure with variable framerate interlaced video, so far I didn't find any kind VFR interlaced video. mostly analouge TV run in CFR.

I using -vsync passthrough let copy frame without droping or adding frame, this allow VFR video converted to VFR at the end, letting FFms indexing VFR video,

if partial frame encoded, try see ffprobe to detect. if MediaInfo and FFprobe return same value, yes... I need adjust -vsync properly...

**Comment by Anime4000** [comment]
This issue has been fixed since version 4.9.3 :tada:

**Comment by DarkShadow44** [comment]
Well, I just updated to 4.9.3 and still have the same problems.  :/

**Comment by Anime4000** [comment]
Variable Frame-rate I set to `-vsync 0` it cause copy frame without modifying total of frame,
https://github.com/Anime4000/IFME/blob/master/ifme/frmMain.cs#L1570
https://ffmpeg.org/ffmpeg.html#Advanced-options

If can, can you send the file to me? using Google Drive or any cloud based service.

**Comment by SailorOnDaTea** [comment]
does this work if I directly reply to this email?

maybe it should behave like windows themes. when you change anything on it without saving, it creates an unsaved theme and switches to it. then leaves the rest untoched. as long as you don't save it manually it keeps writing on this unsaved profile like autosave.
I think that this "Changes applied in realtime" behavior is much more like Linux. but is useful like autosave on games.

--- Original Message ---

**Comment by Anime4000** [comment]
@SailorOnDaTea it's works :smile: by replying email, settings saved when closing form/application exit.
@DarkShadow44 said using `-vsync vfr` works with VFR video, but I tried `-vsync -1` (passthrough) works too, I using mp4 file from my camera phone.

Ok, I try again using `-vsync vfr` without `timecodes.txt` I hope it's works.

**Comment by DarkShadow44** [comment]
I made a demo video to show the issue and uploaded it to mediafire: [testVideo.mkv](http://www.mediafire.com/watch/co1zdodo0vc5rtd/testVideo.mkv)
Just download and convert with IFME, on veryfast is good enough.

The video is basically just a number that gets counted up, the last number that's displayed is 2000.
If encoded it stops at ~11:18, the last 8 seconds are dropped and the last displayed number is 1976.

The amount of frames that is dropped seems random, but this should be enough to show where the problem is.

**Comment by Anime4000** [comment]
Later I at home, I test it :+1: 
Let see current ffmpeg detect and decode, all based on FFmpeg, if FFmpeg stop, x265 also stop.

**Comment by Anime4000** [comment]
![ifme detect fps](https://cloud.githubusercontent.com/assets/1908715/6555175/767ea768-c69e-11e4-9c67-a0881115eb1d.PNG)

FFprobe did not detect total frame, while MediaInfo detect under 29.97 fps and 30.303fps (original)

AVIDEMUX... hmmm

**Comment by Anime4000** [comment]
OK, I done some temporary patch,
on my end, it display all frame :loop: 
try this: https://github.com/Anime4000/IFME/releases/tag/v4.9.3.1

you may override or make backup `ifme.exe` and `ifme.framework.dll`

**Comment by DarkShadow44** [comment]
Doesn't work for me either.
I found the following information, and think that explains the problem fairly well: [GitHub - mkvtoolnix - Wrong frame rate displayed](https://github.com/mbunkus/mkvtoolnix/wiki/Wrong-frame-rate-displayed)
It seems that MKV container just don't care about frame rate, so tools like Mediainfo try to guess it. In my case wrong, which causes the video to get messed up.
In your temporary patch, you wrote about a fix for CFR video, but my video isn't constant frame rate. I know, MediaInfo says it is, but it isn't. If you put the video steam into a different container (simply mux it into MP4 for example), then you see it is VFR. And because MediaInfo interprets it wrong, it can't get encoded the right way - VFR video treated like CFR it will probably go wrong. But I can't think of another way than always to use timestamps if working with MKV. Because as I said, MKV simply doesn't care about framerate and I don't know any way to extract it from the video stream.

**Comment by Anime4000** [comment]
well, FFprobe and MediaInfo detect that file as CFR with Original FPS,
to get VFR video, it need and to have `timecodes.txt` file.

I test so many VFR video including from AMD GE (Game DVR), Digial Camera and Smart Phone, most of them using VFR to save space.

as you say, if container put wrong info, it become wrong when pass info to IFME.

**Comment by SailorOnDaTea** [comment]
Okay looks like if the input doesn't report specifically or missing some information then program simply takes it as CFR. You said in order to detect it you would need some metafile like timecodes.txt but it is not always available right?

This is similar to my previous problem with broken mpeg streams. If we assumed input as perfect then converting didn't work. We needed to analyze/recheck stream to workaround. Simply a more flexible/forgiving ifme could get it done. it was its weakness to be strict but improved it later. Maybe in case of VFR it is better to approach in a similar way.

I think this is like antivirus software. When it has predefined data/definitions it can compare and deal with already recognized files but when there is no information? Heuristic scan! In past antivirus couldn't catch such files but now they block it with heuristic method even if they are not in database.

Is it pissible to detect if video is CFR or VFR this way?

--- Original Message ---

**Comment by Anime4000** [comment]
Once you lose some info about VFR (lose `timecodes.txt`) you cannot make it work without `timecodes.txt`, even FFmpeg detect it as CFR because metadata set to CFR.

VFR video very unature on some device like SmartTV, CFR are preferable.
VFR is one way to save disk space, for example:

30 second of contain one scene, VFR only contain one frame, CFR duplicate it and tell next frame refer to previous.

**Comment by Anime4000** [comment]
IFME Go (v5.x) VFR support natively, but it taking time to indexing first just like x264 ffms
